import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
	return (
		<nav className="flex w-full items-center justify-between p-4 text-xl font-semibold border-b mb-8">
			<div className="w-1/4 links flex items-center justify-between">
				<div>Character Sheet</div>
				<div>Form</div>
			</div>
			<div>Sign In</div>
		</nav>
	)
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<body>
				<TopNav />
				{children}
			</body>
		</html>
	);
}
