import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "~/components/TopNav";
import { Toaster } from "sonner";

export const metadata = {
  title: "DC20-Beyond",
  description: "Generated by loyal subscriber to Theo on YouTube",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type PropTypes = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: PropTypes) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable} dark`}>
        <body>
          <TopNav />
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
